spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://oregon-postgres.render.com:5432/apple_n3hh
    username: apple_n3hh_user
    password: k08QpfbyvO5UUugQpVj49srinUKCdQLB

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

api:
  key: 249f222afb1002186f4d88b2b5418b55
  baseApi: https://api.themoviedb.org/3/search/movie
